// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ncond.jpower.domain;

import com.ncond.jpower.domain.JPowerUser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect JPowerUser_Roo_Configurable {
    
    declare @type: JPowerUser: @Configurable;
    
}
